### ISSUE TITLE
Never get past loginscreen

### ISSUE THREAD

**Issue by rschellius** [RisingStack/nodehero-authentication#2]
I never get past the loginscreen, even when I use the test-user/test-password credentials. It seems like the authenticated user is not available in the next requests. req.isAuthenticated() always fails.

**Comment by mikeleonardonline** [comment]
Unfortunately i also can't get past the loginscreen. I just wasted a few hours trying to get guids and stuff. Wasting time....
This was my initial error:
express-session deprecated req.secret; provide secret option at app\index.js:19:9

**Comment by mikeleonardonline** [comment]
I got past this problem by just using this and rebooting.

app.use(session({
  secret: 'keyboard cat',
  resave: true,
  saveUninitialized: true
}))

For some reason if i type the password wrong, that's it. I had to reboot. If i figure out why i'll let you know. Now i will try to get Redis or a db working.....

**Comment by bluemix** [comment]
thanks @mikeleonardonline , your solution worked with me.

**Comment by redcinelli** [comment]
Hey guys I may have found a solution using redis :)
`app.use(session({
  store: new RedisStore({
    host: "localhost",
    port:6379,
    ttl : 60
  }),
  secret: "plop",
  resave: false,
  saveUninitialized: false
}))
`
You will have to run on localhost your redis-server.

In fact it would be better to edit the config file to match your redis setup.

**Comment by perkrlsn** [comment]
The application is looking for the secret in the **config** file, which in turn is looking for the secret in the environment variables.

Create a file in the root directory called **.env** (or _whateveryouwant.env_) and add this line to it:
```bash
export REDIS_STORE_SECRET=supersecret
```
(This is also where you would add the URI and PORT to the redis-server and a lot of other cool stuff.)

In **package.json** add:
```json
"scripts": {
    "start-dev": "source .env; node index.js"
}
```

And start the application with
```bash
npm run start-dev
```

**Comment by hekike** [comment]
Thanks for helping with this! I improved the README with this information.
